### PR TITLE
Remove special characters for zabbix send2opsgenie.go

### PR DESCRIPTION
**Pull request by MeralBusraTekinsen**

### CODE REVIEW

**Review by cglrkn — APPROVED** [review]

**Comment by sachazufferey** [comment]
Can I ask why?

The alert on Zabbix is "/dir1/dir2 : Disk space is low (used > 80%)" and becomes : "dir1dir2 Disk space is low used 80" on Opsgenie. We have alerts for directory monitoring and the removal of special characters makes it difficult to read.

Did you encounter any problems with sending special characters?

I've edited the sens2opsgenie.go and removed the "removeSpecialCharacters" to test it.

**Comment by MikeN123** [comment]
Why was this done? 🥲

**Comment by salfers** [comment]
This change makes for incredibly confusing alert messages:
grafik
grafik

@cglrkn @MeralBusraTekinsen can you consider reverting this change?

**Comment by mcbrineellis** [comment]
I recompiled send2opsgenie.go myself as well to fix this issue.  Not impressed with how unresponsive Atlassian is with this product.

**Comment by hamadodene** [comment]
@cglrkn Why did you remove special characters? Many of my trigger that contained URLs are broken. Is threre a valid reason for this? It is possibile to bypass this? 
Many you can add a description to this PR with the motivation.

**Comment by mcbrineellis** [comment]
@hamadodene since it’s clear that they aren’t responsive here, you should probably open a support ticket. I would recommend editing the source code as a workaround. It’s working stable for me.

**Comment by hamadodene** [comment]
Thanks @mcbrineellis i will try to edit source code. I am still trying to understand the purpose of this modification. At least providing a motivation in the pull request description would have been helpful.

**Comment by mcbrineellis** [comment]
Totally agree.  It makes no sense why special characters would be disabled in this case, as it's normal for a trigger name, description, host group to have those, and stripping them makes the alert or description totally unreadable.

**Comment by mcbrineellis** [comment]
Looks like there's an issue open for it on their JIRA: https://jira.atlassian.com/browse/OPSGENIE-1090

I just voted for it.  If you do open a support case maybe you can reference that one.

**Pull request merged**
